### ISSUE TITLE
Support for Arm

### ISSUE THREAD

**Issue by grahamwoodward** [intel/processwatch#15]
Hi I was wondering whether you'd accept a patch that gets Process Watch working on Arm, specifically targeting aarch64? 

I have a patch ready to go but wanted to first check whether it's something you'd be willing to accept, or if you prefer I forked the repo ? 

Thanks

**Comment by matthew-olson-intel** [comment]
Of course it's something I'd accept, y'know, assuming it's nothing *too* crazy.  I'm assuming it's just an extra condition checking the value of `pmu_name`, and some extra logic choosing a `perf` event to use, right?

**Comment by grahamwoodward** [comment]
> Of course it's something I'd accept, y'know, assuming it's nothing _too_ crazy. I'm assuming it's just an extra condition checking the value of `pmu_name`, and some extra logic choosing a `perf` event to use, right?
> 
> Edit: Forgot about disassembly. Is there some disassembler that can handle both x86 and ARM?

So to answer the second question, I've added a dependency on Capstone, it actually supports x86...however I didn't really want to be on the hook for regression testing x86 if we switched to Capstone, although it'd make my patch a bit neater as I could remove some #ifdefs that I've got depending on whether it's compiling for x86 or Arm.

And yeah for the first question, I'm not checking for the pmu_name and using a slightly different event id. Also needed to change the default "categories"

How about I raise a PR and you can see. I'm happy to look at swapping Zydis for Capstone as well, do you have any regression tests internally that do any checking that certain x86 instructions have been correctly decoded that we could use to confirm all is good with Capstone?

**Comment by matthew-olson-intel** [comment]
Sure thing, submit the PR. Capstone could be a good idea; I'll give it a spin.

**Comment by matthew-olson-intel** [comment]
Aight, this is in progress in #17.

**Comment by matthew-olson-intel** [comment]
Fixed by #17!
