### ISSUE TITLE
Accept a list of mnemonics/categories in "filter" parameter

### ISSUE THREAD

**Issue by kkurzacz-intel** [intel/processwatch#2]
This is a feature request. Currently, Process Watch accepts only one `filter` parameter. It would be useful to accept list of them, for example:
```
sudo ./processwatch --filter="POP,PUSH"
```
Potential benefits are:
* better "live" preview on instructions counting when doing basic tests
* easier results preview on CSVs
* possibly better results resolution - if collecting instructions count from selected groups can lead to faster data aquisition

**Comment by matthew-olson-intel** [comment]
This is implemented! I haven't implemented it in CSV mode quite yet, but in the new UI (which prints to `stdout`), you can specify multiple `-f` parameters to specify however many mnemonics or categories you'd like.
